[CLOUD-393] Restore snapshot script which will close indices to be restored

diff --git a/templates/default/snapshot_indices.sh.erb b/templates/default/snapshot_indices.sh.erb
--- a/templates/default/snapshot_indices.sh.erb
+++ b/templates/default/snapshot_indices.sh.erb
@@ -6,11 +6,18 @@ ELKADMIN_KEY=<%= @elkadminKey %>
 ELKADMIN_CERT=<%= @elkadminCert %>
 CACERT=<%= @caCert %>
 SNAPSHOTS_REGISTRY=<%= node['elastic']['base_dir'] %>/snapshots_registry/snapshots_registry.json
+_OS_PORT=<%= node['elastic']['port'] %>
 
 default_snapshot_indices=<%= node['elastic']['snapshot']['indices'] %>
 _help(){
     echo -e "Usage $(basename $0) -r REPOSITORY_NAME [OPTIONS]\n\t-n Optionally set a snapshot id\n\t-i Optionally set the indices to snapshot, default: $default_snapshot_indices"
 }
+
+if ! command -v jq &> /dev/null
+then
+    echo "jq could not be found"
+    exit
+fi
 
 unset -v opensearch_snap_repo
 unset -v snapshot_id
@@ -57,7 +64,7 @@ then
     jq -n '[]' > $SNAPSHOTS_REGISTRY
 fi
 
-snap_out=$(curl --fail -k --key $ELKADMIN_KEY  --cert $ELKADMIN_CERT --cacert $CACERT -XPUT https://$HOSTNAME:9200/_snapshot/${opensearch_snap_repo}/${snapshot_id}?wait_for_completion=true  -H "Content-Type: application/json" -d\
+snap_out=$(curl --fail -k --key $ELKADMIN_KEY  --cert $ELKADMIN_CERT --cacert $CACERT -XPUT https://$HOSTNAME:${_OS_PORT}/_snapshot/${opensearch_snap_repo}/${snapshot_id}?wait_for_completion=true  -H "Content-Type: application/json" -d\
 '
 {
   "indices": '\""$snapshot_indices\""',
