test if rivers already running, if yes, don't try and start them in start scripts

diff --git a/templates/default/start-river.sh.erb b/templates/default/start-river.sh.erb
--- a/templates/default/start-river.sh.erb
+++ b/templates/default/start-river.sh.erb
@@ -20,6 +20,14 @@ lib=$JDBC_IMPORTER_HOME/lib
 rivers=$JDBC_IMPORTER_HOME/rivers
 river_dir="$(dirname $river)" 
 river_pid=${river#$river_dir}.pid
+if [ -f $river_pid ] ; then
+  PID=`cat $river_pid`
+  if [ kill -0 $PID 2> /dev/null ] ; then
+    echo "$river is already running. Cannot start it."
+    exit 2
+  fi
+fi
+
 river_log=$JDBC_IMPORTER_HOME/log/${river#$river_dir}.log
 nohup java -cp "${lib}/*" -Dlog4j.configurationFile=${bin}/log4j2.xml org.xbib.tools.Runner org.xbib.tools.JDBCImporter $river > $river_log 2>&1 &
 echo $! > $rivers/$river_pid
